services:
  test:
    image: node:16-alpine
    command: "npm run jest -- -t 'gov'"
    working_dir: /usr/src/app
    ports:
      - 9227:9227 # debug
    volumes:
      # use local files as source
      - .:/usr/src/app
    environment:
      NODE_ENV: test
      # contains db connection info that matches db service setup below
      CONFIG_FILE: config-test.json
    # waits for db and redis to start
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # colorizes output
    tty: true

  db:
    image: postgres:14-alpine
    # matches config in config-test.json
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test']
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  node_modules:
