module.exports = {
  apps: [
    {
      name: 'tracer',
      script: 'dist/scripts/export/trace.js',
      wait_ready: true,
      listen_timeout: 30000,
    },
    {
      name: 'processor',
      script: 'dist/scripts/export/process.js',
      wait_ready: true,
      listen_timeout: 30000,
    },
    {
      name: 'account-webhooks',
      script: 'dist/scripts/accountWebhooks.js',
      args: ['-c', 'config.accounts.json'],
      kill_timeout: 30000,
    },
    {
      name: 'server_accounts',
      script: 'dist/server/serve.js',
      args: ['-p', '3420', '-c', 'config.accounts.json', '-a'],
      instances: 1,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_juno-testnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3430', '-c', 'config.juno-testnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_juno-mainnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3431', '-c', 'config.juno-mainnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_osmosis-mainnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3432', '-c', 'config.osmosis-mainnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_osmosis-testnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3433', '-c', 'config.osmosis-testnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_stargaze-testnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3434', '-c', 'config.stargaze-testnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_stargaze-mainnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3435', '-c', 'config.stargaze-mainnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_neutron-mainnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3436', '-c', 'config.neutron-mainnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_migaloo-mainnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3437', '-c', 'config.migaloo-mainnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server_migaloo-testnet',
      script: 'dist/server/serve.js',
      args: ['-p', '3438', '-c', 'config.migaloo-testnet.json'],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
}
