apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus
  labels:
    app: argus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argus
  template:
    metadata:
      labels:
        app: argus
    spec:
      containers:
        - name: argus
          image: argus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3420
          env:
            - name: CONFIG_FILE
              value: '/app/config/config.json'
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 3420
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3420
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: argus-config-file
