apiVersion: v1
kind: Service
metadata:
  name: dao-dao-indexer
  labels:
    app: dao-dao-indexer
spec:
  selector:
    app: dao-dao-indexer
  ports:
    - port: 80
      targetPort: 3420
      protocol: TCP
  type: ClusterIP
