/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type AddAuthenticator = {
  Secp256K1: {
    id: number;
    pubkey: Binary;
    signature: Binary;
  };
} | {
  Ed25519: {
    id: number;
    pubkey: Binary;
    signature: Binary;
  };
} | {
  EthWallet: {
    address: string;
    id: number;
    signature: Binary;
  };
} | {
  Jwt: {
    aud: string;
    id: number;
    sub: string;
    token: Binary;
  };
} | {
  Secp256R1: {
    id: number;
    pubkey: Binary;
    signature: Binary;
  };
} | {
  Passkey: {
    credential: Binary;
    id: number;
    url: string;
  };
};
export type Binary = string;
export interface InstantiateMsg {
  authenticator: AddAuthenticator;
}
export type ExecuteMsg = {
  add_auth_method: {
    add_authenticator: AddAuthenticator;
  };
} | {
  remove_auth_method: {
    id: number;
  };
} | {
  emit: {
    data: string;
  };
};
export type QueryMsg = {
  authenticator_i_ds: {};
} | {
  authenticator_by_i_d: {
    id: number;
  };
};
export interface MigrateMsg {}
export type Authenticator = {
  secp256_k1: {
    pubkey: Binary;
  };
} | {
  ed25519: {
    pubkey: Binary;
  };
} | {
  eth_wallet: {
    address: string;
  };
} | {
  jwt: {
    aud: string;
    sub: string;
  };
} | {
  secp256_r1: {
    pubkey: Binary;
  };
} | {
  passkey: {
    passkey: Binary;
    url: string;
  };
};
export type ArrayOfUint8 = number[];