/**
 * This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-5.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @abstract-money/ts-codegen generate command to regenerate this file.
 */

export type Uint128 = string
export interface InstantiateMsg {
  admin: string
  namespace_registration_fee?: Coin | null
  security_enabled?: boolean | null
}
export interface Coin {
  amount: Uint128
  denom: string
}
export type ExecuteMsg =
  | {
      remove_module: {
        module: ModuleInfo
      }
    }
  | {
      yank_module: {
        module: ModuleInfo
      }
    }
  | {
      propose_modules: {
        modules: [ModuleInfo, ModuleReference][]
      }
    }
  | {
      update_module_configuration: {
        module_name: string
        namespace: Namespace
        update_module: UpdateModule
      }
    }
  | {
      approve_or_reject_modules: {
        approves: ModuleInfo[]
        rejects: ModuleInfo[]
      }
    }
  | {
      claim_namespace: {
        account_id: AccountId
        namespace: string
      }
    }
  | {
      forgo_namespace: {
        namespaces: string[]
      }
    }
  | {
      add_account: {
        creator: string
        namespace?: string | null
      }
    }
  | {
      update_config: {
        namespace_registration_fee?: ClearableForCoin | null
        security_enabled?: boolean | null
      }
    }
  | {
      update_ownership: Action
    }
export type Namespace = string
export type ModuleVersion =
  | 'latest'
  | {
      version: string
    }
export type ModuleReference =
  | {
      account: number
    }
  | {
      native: Addr
    }
  | {
      adapter: Addr
    }
  | {
      app: number
    }
  | {
      standalone: number
    }
  | {
      service: Addr
    }
export type Addr = string
export type UpdateModule =
  | {
      default: {
        metadata: string
      }
    }
  | {
      versioned: {
        instantiation_funds?: Coin[] | null
        metadata?: string | null
        monetization?: Monetization | null
        version: string
      }
    }
export type Monetization =
  | 'none'
  | {
      install_fee: FixedFee
    }
export type AccountTrace =
  | 'local'
  | {
      remote: TruncatedChainId[]
    }
export type TruncatedChainId = string
export type ClearableForCoin =
  | 'clear'
  | {
      set: Coin
    }
export type Action =
  | {
      transfer_ownership: {
        expiry?: Expiration | null
        new_owner: string
      }
    }
  | 'accept_ownership'
  | 'renounce_ownership'
export type Expiration =
  | {
      at_height: number
    }
  | {
      at_time: Timestamp
    }
  | {
      never: {}
    }
export type Timestamp = Uint64
export type Uint64 = string
export interface ModuleInfo {
  name: string
  namespace: Namespace
  version: ModuleVersion
}
export interface FixedFee {
  fee: Coin
}
export interface AccountId {
  seq: number
  trace: AccountTrace
}
export type QueryMsg =
  | {
      accounts: {
        account_ids: AccountId[]
      }
    }
  | {
      modules: {
        infos: ModuleInfo[]
      }
    }
  | {
      namespaces: {
        accounts: AccountId[]
      }
    }
  | {
      namespace: {
        namespace: Namespace
      }
    }
  | {
      config: {}
    }
  | {
      account_list: {
        limit?: number | null
        start_after?: AccountId | null
      }
    }
  | {
      module_list: {
        filter?: ModuleFilter | null
        limit?: number | null
        start_after?: ModuleInfo | null
      }
    }
  | {
      namespace_list: {
        limit?: number | null
        start_after?: string | null
      }
    }
  | {
      ownership: {}
    }
export type ModuleStatus = 'registered' | 'pending' | 'yanked'
export interface ModuleFilter {
  name?: string | null
  namespace?: string | null
  status?: ModuleStatus | null
  version?: string | null
}
export type MigrateMsg =
  | {
      instantiate: InstantiateMsg
    }
  | {
      migrate: {}
    }
export type AccountForAddr = Addr
export interface AccountListResponse {
  accounts: [AccountId, AccountForAddr][]
}
export interface AccountsResponse {
  accounts: AccountForAddr[]
}
export interface ConfigResponse {
  local_account_sequence: number
  namespace_registration_fee?: Coin | null
  security_enabled: boolean
}
export interface ModulesListResponse {
  modules: ModuleResponse[]
}
export interface ModuleResponse {
  config: ModuleConfiguration
  module: Module
}
export interface ModuleConfiguration {
  instantiation_funds: Coin[]
  metadata?: string | null
  monetization: Monetization
}
export interface Module {
  info: ModuleInfo
  reference: ModuleReference
}
export interface ModulesResponse {
  modules: ModuleResponse[]
}
export type NamespaceResponse =
  | {
      claimed: NamespaceInfo
    }
  | {
      unclaimed: {}
    }
export interface NamespaceInfo {
  account: AccountForAddr
  account_id: AccountId
}
export interface NamespaceListResponse {
  namespaces: [Namespace, AccountId][]
}
export interface NamespacesResponse {
  namespaces: [Namespace, AccountId][]
}
export interface OwnershipForString {
  owner?: string | null
  pending_expiry?: Expiration | null
  pending_owner?: string | null
}
